/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
/**
 *
 * @author UPC
 */
public class ViewMenuBendahara extends javax.swing.JFrame implements View {

    /**
     * Creates new form MenuBendahara
     */
    public ViewMenuBendahara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnBelanja = new javax.swing.JButton();
        BtnPenerimaan = new javax.swing.JButton();
        BtnJurnal = new javax.swing.JButton();
        BtnPosting = new javax.swing.JButton();
        BtnTutupBuku = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnBelanja.setText("Transaksi Belanja");

        BtnPenerimaan.setText("Transaksi Penerimaan");

        BtnJurnal.setText("Jurnal");

        BtnPosting.setText("Posting");

        BtnTutupBuku.setText("Tutup Buku");

        BtnLogout.setText("Log out");

        jLabel1.setText("Menu Bendahara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnLogout)
                    .addComponent(BtnTutupBuku)
                    .addComponent(BtnPosting)
                    .addComponent(BtnJurnal)
                    .addComponent(BtnPenerimaan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnBelanja)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBelanja)
                .addGap(18, 18, 18)
                .addComponent(BtnPenerimaan)
                .addGap(18, 18, 18)
                .addComponent(BtnJurnal)
                .addGap(18, 18, 18)
                .addComponent(BtnPosting)
                .addGap(18, 18, 18)
                .addComponent(BtnTutupBuku)
                .addGap(18, 18, 18)
                .addComponent(BtnLogout)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBelanja;
    private javax.swing.JButton BtnJurnal;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnPenerimaan;
    private javax.swing.JButton BtnPosting;
    private javax.swing.JButton BtnTutupBuku;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        BtnBelanja.addActionListener(e);
        BtnJurnal.addActionListener(e);
        BtnPenerimaan.addActionListener(e);
        BtnPosting.addActionListener(e);
        BtnTutupBuku.addActionListener(e);
        BtnLogout.addActionListener(e);
    }

    @Override
    public void viewErrorMsg(String errorMsg) {
        JOptionPane.showMessageDialog(this, errorMsg);
    }

    public Object getBtnBelanja() {
        return BtnBelanja;
    }

    public Object getBtnJurnal() {
        return BtnJurnal;
    }

    public Object getBtnLogout() {
        return BtnLogout;
    }

    public Object getBtnPenerimaan() {
        return BtnPenerimaan;
    }

    public Object getBtnPosting() {
        return BtnPosting;
    }

    public Object getBtnTutupBuku() {
        return BtnTutupBuku;
    }
}
